### ISSUE TITLE
Global water fluxes

### ISSUE THREAD

**Issue by wande001** [JannisHoch/pcrglobwb_utils#11]
* pcrglobwb_utils version: 0.1
* Python version: 3
* Operating System: MAC

### Description

Ability to use log file or other input to compute global water fluxes

### What I Did

```
Using LOG file as an input or netCDF files, see my PCR-GLOBWB validation script
```

**Comment by JannisHoch** [comment]
@wande001 
implemented in this commit:

https://github.com/JannisHoch/pcrglobwb_utils/commit/e0ae30bab6402e0acc02fe8ffc214e118907485d
